
version: '3.7'

services:
  supernova-dev:
    container_name: supernova-dev
    build: .
    environment:
      SUPERNOVA_DEBUG: true
    env_file:
      # - ~/+vault/local/supernova/env
      - ~/+vault/@me/git-ci/env/supernova.env
    volumes:
      - type: bind
        # source: ./supernova-dev/config.yml
        source: ~/Development/@me/up/git-ci/src/supernova/config.yml
        target: /etc/supernova/config.yml
        read_only: true
      - type: bind
        source: ./supernova-dev/repos
        target: /var/supernova/repos
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - 48214:9000
