
steps:
  - name: Clone/pull git repository
    image: simplepackages/git
    commands:
      - echo '[url "https://'$GIT_TOKEN'@'$GIT_URL_HOSTNAME'"]' > ~/.gitconfig
      - echo 'InsteadOf = https://'$GIT_URL_HOSTNAME >> ~/.gitconfig
      - git clone -b $GIT_BRANCH --single-branch $GIT_URL . || true
      - git pull
      - GIT_COMMIT: git rev-parse HEAD
      - GIT_COMMIT_SHORT: git rev-parse --short HEAD
  - /next
